<?php

declare(strict_types=1);

/**
 * PostgreSQL compatibility/bootstrap for the legacy Samaaroh PHP application.
 *
 * The original MySQL schema used TINYINT(1) for boolean-like fields, while
 * PostgreSQL can represent them as BOOLEAN. The application consistently
 * reads/writes legacy 0/1 values, so we normalize every public BOOLEAN column
 * to INTEGER with 0/1 semantics before Apache starts.
 *
 * This bootstrap also creates the two catering/gallery support tables used by
 * the application but absent from the older phpMyAdmin data-dictionary export.
 * Everything is idempotent.
 */

$databaseUrl = trim((string) getenv('DATABASE_URL'));

if ($databaseUrl === '') {
    exit(0);
}

$parts = parse_url($databaseUrl);
if ($parts === false || empty($parts['host'])) {
    fwrite(STDERR, "Invalid DATABASE_URL.\n");
    exit(1);
}

$host = $parts['host'];
$port = $parts['port'] ?? 5432;
$db = ltrim((string) ($parts['path'] ?? ''), '/');
$user = rawurldecode((string) ($parts['user'] ?? ''));
$pass = rawurldecode((string) ($parts['pass'] ?? ''));

if ($db === '' || $user === '') {
    fwrite(STDERR, "DATABASE_URL is missing database or username.\n");
    exit(1);
}

$dsn = sprintf(
    'pgsql:host=%s;port=%s;dbname=%s;sslmode=require',
    $host,
    $port,
    $db
);

$pdo = new PDO($dsn, $user, $pass, [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => false,
]);

function qident(string $identifier): string
{
    return '"' . str_replace('"', '""', $identifier) . '"';
}

// ============================================================
// APP-SPECIFIC TABLES NOT PRESENT IN THE OLDER DICTIONARY EXPORT
// ============================================================
// Catering confirmation inserts into catering_bookings.
$pdo->exec(<<<'SQL'
CREATE TABLE IF NOT EXISTS "catering_bookings" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "service_id" BIGINT NOT NULL,
    "customer_id" BIGINT NOT NULL,
    "provider_id" BIGINT NOT NULL,
    "event_date" DATE NOT NULL,
    "event_time" TIME NOT NULL,
    "venue_location" TEXT NOT NULL,
    "contact_person" VARCHAR(255) NOT NULL,
    "mobile_number" VARCHAR(30) NOT NULL,
    "special_requirements" TEXT,
    "guest_count" INTEGER DEFAULT 50,
    "selected_menu" JSONB,
    "total_cost" NUMERIC(12,2) NOT NULL,
    "status" TEXT DEFAULT 'pending'
        CHECK ("status" IN ('pending', 'accepted', 'confirmed', 'cancelled', 'completed')),
    "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
SQL);

$pdo->exec(<<<'SQL'
CREATE INDEX IF NOT EXISTS "idx_catering_bookings_service"
    ON "catering_bookings" ("service_id")
SQL);

$pdo->exec(<<<'SQL'
CREATE INDEX IF NOT EXISTS "idx_catering_bookings_customer"
    ON "catering_bookings" ("customer_id")
SQL);

$pdo->exec(<<<'SQL'
CREATE INDEX IF NOT EXISTS "idx_catering_bookings_provider"
    ON "catering_bookings" ("provider_id")
SQL);

$pdo->exec(<<<'SQL'
CREATE INDEX IF NOT EXISTS "idx_catering_bookings_status"
    ON "catering_bookings" ("status")
SQL);

// Provider gallery uploads use service_gallery.
$pdo->exec(<<<'SQL'
CREATE TABLE IF NOT EXISTS "service_gallery" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "service_id" BIGINT NOT NULL,
    "image_name" VARCHAR(255) NOT NULL,
    "image_path" VARCHAR(500) NOT NULL,
    "display_order" INTEGER DEFAULT 0,
    "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
SQL);

$pdo->exec(<<<'SQL'
CREATE INDEX IF NOT EXISTS "idx_service_gallery_service"
    ON "service_gallery" ("service_id")
SQL);

$pdo->exec(<<<'SQL'
CREATE INDEX IF NOT EXISTS "idx_service_gallery_display_order"
    ON "service_gallery" ("display_order")
SQL);

// ============================================================
// CATERING-SPECIFIC SERVICE COLUMNS
// ============================================================
$serviceColumnDefinitions = [
    'menu_data' => 'JSONB',
    'is_fixed_thali' => 'INTEGER DEFAULT 0',
    'thali_price_per_person' => 'NUMERIC(10,2) DEFAULT 0.00',
    'fixed_thali_menu' => 'TEXT',
];

foreach ($serviceColumnDefinitions as $column => $definition) {
    $check = $pdo->prepare(
        'SELECT 1 FROM information_schema.columns '
        . 'WHERE table_schema = \'public\' AND table_name = \'services\' AND column_name = ?'
    );
    $check->execute([$column]);

    if ($check->fetchColumn() === false) {
        $pdo->exec(
            'ALTER TABLE ' . qident('services')
            . ' ADD COLUMN ' . qident($column) . ' ' . $definition
        );
        echo "Added public.services.{$column}.\n";
    }
}

// ============================================================
// LEGACY BOOLEAN COMPATIBILITY
// ============================================================
$booleanColumns = $pdo->query(
    "SELECT table_name, column_name, column_default\n" .
    "FROM information_schema.columns\n" .
    "WHERE table_schema = 'public'\n" .
    "  AND data_type = 'boolean'\n" .
    "ORDER BY table_name, ordinal_position"
)->fetchAll();

$converted = 0;

foreach ($booleanColumns as $column) {
    $table = (string) $column['table_name'];
    $name = (string) $column['column_name'];
    $default = $column['column_default'];

    $qTable = qident($table);
    $qColumn = qident($name);

    $pdo->exec("ALTER TABLE {$qTable} ALTER COLUMN {$qColumn} DROP DEFAULT");
    $pdo->exec(
        "ALTER TABLE {$qTable} ALTER COLUMN {$qColumn} TYPE INTEGER " .
        "USING CASE WHEN {$qColumn} IS TRUE THEN 1 ELSE 0 END"
    );

    if ($default !== null) {
        $defaultValue = preg_match('/TRUE/i', (string) $default) ? '1' : '0';
        $pdo->exec(
            "ALTER TABLE {$qTable} ALTER COLUMN {$qColumn} SET DEFAULT {$defaultValue}"
        );
    }

    $converted++;
    echo "Converted public.{$table}.{$name} BOOLEAN -> INTEGER.\n";
}

$remaining = $pdo->query(
    "SELECT COUNT(*) FROM information_schema.columns " .
    "WHERE table_schema = 'public' AND data_type = 'boolean'"
)->fetchColumn();

if ((int) $remaining !== 0) {
    throw new RuntimeException(
        "PostgreSQL compatibility check failed: {$remaining} BOOLEAN column(s) remain."
    );
}

echo "PostgreSQL legacy-boolean compatibility check complete. {$converted} column(s) normalized.\n";
